{
 "title": "Cloud Watch",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Indicadores de falhas no hardware",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-00ee3c7f43edc4505" },
     "label": "Grafana",
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-034f36a5e51cb5dee" },
     "label": "Kafka",
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-0a8154bf46c731d4a" },
     "label": "Jupyter",
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Indicadores de falhas na instância",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-00ee3c7f43edc4505" },
     "label": "Grafana",
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-034f36a5e51cb5dee" },
     "label": "Kafka",
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-0a8154bf46c731d4a" },
     "label": "Jupyter",
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Utilização da CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-00ee3c7f43edc4505" },
     "label": "Grafana",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-034f36a5e51cb5dee" },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-0a8154bf46c731d4a" },
     "label": "Jupyter",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Tráfego de entrada e saída",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-00ee3c7f43edc4505" },
     "label": "Grafana IN",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-034f36a5e51cb5dee" },
     "label": "Kafka IN",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-0a8154bf46c731d4a" },
     "label": "Jupyter IN",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-00ee3c7f43edc4505" },
     "label": "Grafana OUT",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-034f36a5e51cb5dee" },
     "label": "Kafka OUT",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-0a8154bf46c731d4a" },
     "label": "Jupyter OUT",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}